apiVersion: v1

kind: Pod

metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
    assistant: omotolani

spec:
  containers:
    - name: nginx-container
      image: nginx
#    - name: ubuntu:latest
#      image: ubuntu
#


      
